### ISSUE TITLE
Non positive weights

### ISSUE THREAD

**Issue by m-couldrey** [NCAS-CMS/cf-python#39] opened 2020-03-16 09:14 UTC
cf.environment(paths=False)
Platform: Linux-2.6.32-754.25.1.el6.x86_64-x86_64-with-redhat-6.10-Santiago
HDF5 library: 1.10.5
netcdf library: 4.7.3
udunits2 library: /home/users/mpc18/miniconda3/lib/libudunits2.so.0
python: 3.7.4
netCDF4: 1.5.3
cftime: 1.0.4.2
numpy: 1.18.1
psutil: 5.7.0
scipy: 1.4.1
matplotlib: 3.1.3
ESMF: 8.0.0
cfdm: 1.7.11
cfunits: 3.2.4
cfplot: 3.0.5
cf: 3.1.0

Hi I'm trying to calculate an area-weighted mean of a (seemingly) cf compliant field. When I call g.collapse('X: Y: mean',weights='area') I get ValueError: All weights must be positive. Got a weight of [0.0] m

The same also results when I attempt to make any call to the areas/weights (e.g. g.cell_area() or g.weights('area')

Not sure what's going wrong here. I'm not expecting or wanting any weights to be non-positive. This collapse used to work on the same data in cfpython 2. The file containing the field can be found on jasmin at /home/users/mpc18/zos_Oyr_MIROC6_FAF-heat_r1i1p1f1_gn_320001-326912.nc

Cheers!

**Comment by sadielbartholomew** [comment] 2020-03-17 14:17
Thanks for reporting this @m-couldrey. I'll look into it later this afternoon & get back to you soon.

**Comment by sadielbartholomew** [comment] 2020-03-21 00:39
To report back: in short, **I am confident this is not a bug in ``cf-python``, but rather dubious data components (those recorded at ``>90`` degree latitude) in the field leading to numerous calculated cell area weights of zero, which``cf-python`` is correctly processing & reporting on**.

I've provided more detail below to back-up this conclusion, & to suggest how you might be able to progress with an area collapse given the nature of the field.

I've also sought a second opinion from @davidhassell who agrees with the above, so unless you have any comments in reponse to the summary below, or otherwise, we will remove the 'bug' tag and close this Issue. Thanks.

### Are there any non-positive weights? (``cf-python`` v.3)

**Short answer: yes**

Firstly, I have recreated the error you observed for all three methods mentioned. I added in a compound print statement to see what is happening under-the-hood just before it hits the error (where ``w`` are the cell area weights):

```diff
diff --git a/cf/field.py b/cf/field.py
index 615ef4f..6b6c0ee 100644
--- a/cf/field.py
+++ b/cf/field.py
@@ -5719,6 +5719,8 @@ class Field(mixin.PropertiesData,
         # --- End: if
 
         for w in comp.values():
+            from numpy import count_nonzero
+            print(len(w.array), count_nonzero(w.array), w.array)
             mn = w.min()
             if mn <= 0:
                 raise ValueError(
```

& with that added to give the number of elements in the NumPy array, the number of non-zero ones, and the array itself to double-check, I see this:

```python
>>> import cf
>>> cf.__version__
'3.1.0'
>>> g = cf.read('~/zos_Oyr_MIROC6_FAF-heat_r1i1p1f1_gn_320001-326912.nc')[0]
>>> g.cell_area()
360 360 [111198.92344855 111198.92344855 111198.92344855 111198.92344855
 111198.92344855 111198.92344855 111198.92344855 111198.92344855

... [output cropped for brevity] ...

 111198.92344855 111198.92344855 111198.92344855 111198.92344855
 111198.92344855 111198.92344855 111198.92344855 111198.92344855]
256 223 [ 15519.99362715   4120.37908967   4604.07715481   5087.42460165
   5570.38462141   6052.92043482   6534.9952949    7016.57248979

 ... [output cropped for brevity, but all positive values] ...

  65217.84008062  58703.70364579  52126.70581472  45493.88940144
  38812.35699188  32089.26333832  25331.80769782  18547.22612315
  11742.78371419   4925.76683831    168.1737756       0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.
      0.              0.              0.              0.        ]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/cf-python/cf/field.py", line 4415, in cell_area
    w = self.weights('area', radius=radius, measure=True, scale=None)
  File "/home/vagrant/cf-python/cf/field.py", line 5727, in weights
    "All weights must be positive. Got a weight of {}".format(mn))
ValueError: All weights must be positive. Got a weight of [0.0] m
```

From that I see the 360 longitude-based weights are all positive, but for the latitudes, only 223 of 256 are positive and the remainder ``0.``, all of those being at the end of the weights array as above. (I also see the equivalent output with calls to ``g.weights('area')`` & ``g.collapse('X: Y: mean', weights='area')``, naturally as they all go via the ``weights()`` method where I added the print statement.)

So *there are in fact weights which are non-positive*. The question becomes *why* there are (see the next-but-one section).


### Are there any non-positive weights? (``cf-python`` v.2)

> This collapse used to work on the same data in cfpython 2

Are you sure, & if so can you remember the specific version you saw a successful collapse with? Was the dataset was exactly as-is when you saw it work for a v.2 i.e. has it perhaps been changed since (there are some changes indicated from late 2018 via ``g.get_property('history')``)?

I ask as I tested the same method calls with the latest (final) cf-python 2 version, 2.3.8, under a Python 2 environment, & it still threw an error which on further inspection resulted from the same weight array, with ~30 elements being zero.

This makes me doubt that you had seen the collapse work without error for the precise same dataset with a cf-python v.2. In fact, the context as outlined below implies that it wouldn't make sense for such a collapse to work.


### Why there are non-positive weights

**Short answer: `cf-python` calculates the weights from the bounds as there are no area cell measures. Given the metadata it is assuming a lat-lon grid but there are latitude values over 90 degrees which it clips because they don't make sense on that grid.**

There are no area cell measure constructs defined for the field from the dataset, which means (see the [`weights` method API reference](https://ncas-cms.github.io/cf-python/method/cf.Field.weights.html?highlight=weights#cf.Field.weights)) that cf-python calculates cell areas from the bounds of the latitude & longitude dimension coordinate constructs.

Looking at the latitude dimension, for which the zero weights emerge, the bounds are defined properly but the values towards the end of the corresponding data array are all greater than 90 degrees:

```python
>>> import cf
>>> g = cf.read('~/zos_Oyr_MIROC6_FAF-heat_r1i1p1f1_gn_320001-326912.nc')[0]
>>> g.dim('Y').bounds.array
array([[-90.        , -86.        ],
       [-86.        , -85.5       ],
       [-85.5       , -85.        ],
       [-85.        , -84.5       ],
       [-84.5       , -84.        ],
       [-84.        , -83.5       ],
       [-83.5       , -83.        ],

... [output cropped for brevity, but monotonically increasing] ...

       [-71.        , -70.5       ],
       [-70.5       , -70.        ],
       [-70.        , -69.5       ],
       [-69.5       , -68.99254011],
       [-68.99254011, -68.4775637 ],
       [-68.4775637 , -67.95501576],
       [-67.95501576, -67.42484294],

... [ditto] ...

       [143.95870028, 145.83370028],
       [145.83370028, 147.70870028],
       [147.70870028, 149.58370028],
       [149.58370028, 151.45870028],
       [151.45870028, 153.33370028]])
```

The elements corresponding to the zero weights are those with the latitude values of over 90, since from the first section there are 33 and that is the exact number of bounds elements where both values are above 90 (``(67-1)/2``, where the 1 is deducted to account for the single ``[False, True]` item counted:

```python
>>> g.dim('Y').bounds.array == cf.Query('ge', 90)
array([[False, False],
       [False, False],
       [False, False],

 ... [output cropped for brevity, but all the same as directly above] ...

       [False, False],
       [False,  True],
       [ True,  True],
       [ True,  True],

... [output cropped for brevity, but all the same as directly above] ...

       [ True,  True],
       [ True,  True]])
>>> import numpy
>>> values_over_90 = g.dim('Y').bounds.array == cf.Query('ge', 90)
>>> numpy.count_nonzero(values_over_90)
67
```

``cf-python`` assumes the data is on a standard lat-lon grid where ``>90`` latitude values are un-physical hence it clips those (see [the `clip` API reference](https://ncas-cms.github.io/cf-python/method/cf.Bounds.clip.html?highlight=clip#cf.Bounds.clip)) to 90, meaning it interprets ``[90, 90]`` bounds as ``[90, 90]`` and hence takes the latitude component towards the cell area to have zero length, naturally resulting in an area of zero.


### Is there a workaround?

**Short answer: I don't think so, unless you manipulate your data to remove or amend the ``>90`` latitude bound values whilst preserving the nature of the data you want to capture.**

I see that the field is defined on a tripolar domain:

```python
>>> g.get_property('grid')
'native ocean tripolar grid with 360x256 cells'
```

I don't know much about that particular grid. Would you expect to see `>90` degree latitude values there? What do they mean in the context of the grid - can you convert them to different values that have the same physical meaning with respect to earth surface locations?

For other tripolar-domain fields do you specify the field using the same domain axes & the same units? I do notice you are using 'degrees` for the units of both lat & lon (rather than the standard 'degrees east/north') which I know is used for rotated lat-lon grids, but I am not sure if it is the CF-compliant way to indicate the coordinates for tripolar grids.

I advise you inspect the field to check it makes physical sense (particularly the `>90` latitude bounds), & if you think it does, compare it with another tripolar domain dataset that you know to be CF compliant to see if there is some metadata aspect missing in this field which puts those bounds into a context such that they are recognised as being sensible.

I hope that helps.

**Comment by m-couldrey** [comment] 2020-03-30 10:50
Dear Sadie Bartholomew

Thank you for the very thorough investigation of this. Interesting how this
issue as arisen, I see that it seems not to be a fault with CF and more
likely associated with the particular model that I'm working with.

I don't know much about this particular model or its grid either so I'm not
sure what we "should" see from it, especially at (or beyond?) the North
Pole. I'll try to find some workaround. I clearly found some way to
sidestep this in my code using CF-v2 so I'll try and do the same again
here. I wonder if I implemented something to dodge this issue that I've
forgotten about.

Cheers for your help!
Matthhew

**Comment by sadielbartholomew** [comment] 2020-03-30 14:08
Thanks @m-couldrey, it's always good when possible bugs are reported. No problem, it seems like we agree from the details that is something odd with the model field, but especially given the amount of digging I had to do to see what was really going on it is understandable that it was thought to be a bug.

If you have a specific vision for where you want to get to in a 'workaround' then we are happy to try to help, in which case just send an email over to myself &/or David (Hassell) (since it relates to a specific model rather than cf-python itself probably best located outside of a GitHub Issue).

**Closed by sadielbartholomew** 2020-03-30 14:08 UTC
Labels: bug
