### ISSUE TITLE
cf regridding method

### ISSUE THREAD

**Issue by carlocafaro** [NCAS-CMS/cf-python#162] opened 2020-12-04 17:39 UTC
Hello, 
I am using the conservative method to regrid one field (cp) to another (gpm) and I need to create bounds.

_loncp=cp.dim('X')
latcp=cp.dim('Y')_

If I try: 

_bounds = loncp.create_bounds()
loncp.set_bounds(bounds)_

I got this message:
 _"Can't set bounds: Incorrect shape: {0})".format(bounds.shape))
ValueError: Can't set bounds: Incorrect shape: (1850, 2))_

This is loncp.dump():
_Dimension coordinate: longitude
    axis = 'X'
    standard_name = 'longitude'
    units = 'degrees_east'
    Data(1850) = [340.0, ..., 413.9599914550781] degrees_east

Bounds: X
    units = 'degrees_east'
    Data(1850, 2) = [[339.97999572753906, ..., 413.97999572753906]] degrees_east_

This is the ncump -h of the original file (cp) with the coordinates:

ncdump -h of the source file:

variables:
**float stratiform_rainfall_flux(time, latitude, longitude) ;**
stratiform_rainfall_flux:standard_name = "stratiform_rainfall_flux" ;
stratiform_rainfall_flux:units = "kg m-2 s-1" ;
stratiform_rainfall_flux:um_stash_source = "m01s04i203" ;
stratiform_rainfall_flux:grid_mapping = "latitude_longitude" ;
stratiform_rainfall_flux:coordinates = "forecast_period forecast_reference_time realization" ;

**int latitude_longitude ;**
latitude_longitude:grid_mapping_name = "latitude_longitude" ;
latitude_longitude:longitude_of_prime_meridian = 0. ;
latitude_longitude:earth_radius = 6371229. ;

**double time(time) ;**
time:axis = "T" ;
time:units = "hours since 1970-01-01 00:00:00" ;
time:standard_name = "time" ;
time:calendar = "gregorian" ;

**float latitude(latitude) ;**
latitude:axis = "Y" ;
latitude:units = "degrees_north" ;
latitude:standard_name = "latitude" ;

**float longitude(longitude) ;**
longitude:axis = "X" ;
longitude:units = "degrees_east" ;
longitude:standard_name = "longitude" ;
double forecast_period(time) ;
forecast_period:units = "hours" ;
forecast_period:standard_name = "forecast_period" ;

double forecast_reference_time ;
forecast_reference_time:units = "hours since 1970-01-01 00:00:00" ;
forecast_reference_time:standard_name = "forecast_reference_time" ;
forecast_reference_time:calendar = "gregorian" ;

int realization ;
realization:units = "1" ;
realization:standard_name = "realization" ;

Can you help me with this? Creating the bounds was working in the previous version of cf.

Thanks,
Carlo

**Comment by sadielbartholomew** [comment] 2020-12-10 06:32
Hi Carlo, thanks for raising this. We have been, and still are, really busy since you posted this but just to let you know we are aware you have put up this issue and will try to respond later today or tomorrow.

**Comment by sadielbartholomew** [comment] 2020-12-11 15:58
Hi again @carlocafaro, I've had a look at this now. Unfortunately I can't recreate it nor see anything in the information you have provided that explains why or how you are running into the "Can't set bounds: Incorrect shape" `ValueError`. The shapes of the bounds and the data are compatible for the operations you are running as you are probably aware. I've run various examples to create and set bounds in a similar way and they are all working.

Are you absolutely sure you ran:
```
bounds = loncp.create_bounds()
loncp.set_bounds(bounds)
```
and not accidentally put `latcp` in one statement instead?

I've assumed you are using the latest version of cf-python but you haven't explicitly confirmed this, so perhaps not? Please can you share the output you get when you run `cf.environment()` with us so we know the exact version of `cf` and dependencies you are using? It would also be helpful if you could post the full traceback that emerges, not just the final two lines, if you don't mind. Thanks.

**Comment by carlocafaro** [comment] 2020-12-11 17:08
![image](https://user-images.githubusercontent.com/9113948/101932949-68f5a780-3bd3-11eb-94a8-e2d718e96c8b.png)

This is what I got from cf.environment()

**Comment by davidhassell** [comment] 2020-12-14 16:02
Hi @carlocafaro could you possibly attach in a file the entire output of `ncdump -c FILE` to this issue:

```
$ ncdump -c FILE > FILE.cdl
```

Thanks - then we can see what we can do.

**Comment by davidhassell** [comment] 2022-12-08 09:37
Closing as dormant - please re-open if needs be!

**Closed by davidhassell** 2022-12-08 09:37 UTC
