### ISSUE TITLE
Remembering weights between consecutive regridding operations

### ISSUE THREAD

**Issue by ThibHlln** [NCAS-CMS/cf-python#222] opened 2021-05-27 14:29 UTC
Given two fields `fld1` and `fld2`, if I use for example `regrids` twice, it seems to take the same amount of time the first and the second time.

```python
fld3 = fld1.regrids(fld2, 'conservative')
fld4 = fld1.regrids(fld2, 'conservative')
```

So I am wondering if `cf` is able to remember the weights from the first time it did the regridding in order to make the second time faster?

**Comment by sadielbartholomew** [comment] 2021-05-27 17:09
Hi @ThibHlln, thanks for the very good question as usual!

I will double check in the API and code (if I don't comment further assume it is indeed the case) but I suspect that, at the moment, there is not a way to do so. However, caching the weights is certainly a good idea (if, as I assume in practice, you mean a non-trivial case on , not just repeating the exact same regridding operation twice i.e. maybe the metadata differs?) and I think it would not be difficult to implement something that could do that.

We can mark it as a (performance) feature for the next version, as improving performance is one of the core tasks we are working on at the moment and going forward.

**Comment by davidhassell** [comment] 2021-05-27 19:11
Hi - it certainly was the case that caching the weights was _not_ possible in ESMPy (up to <= 8.0, I think). However, there was a new release a few weeks back, and I must confess that I only skim-read the release notes ... I'll go back and check them more closely for gold. We have engaged with the ESMF team in the past and requested this feature, so they do know that it is desired, but I don't know how hard it is for them to implement.

Thanks,
David

**Comment by ThibHlln** [comment] 2021-05-28 07:07
Hi Sadie and David,

@sadielbartholomew Yes, you are right, my case was rather trivial. Just to give some context, I need to regrid repeatedly (i.e. iterating over time) from one modelling component resolution to another (specified as `cf.Field`, invariant over time). So, only the data would change between iterations, the metadata would remain unchanged. Sp more something like this:

```python
# first iteration
fld1.set_data(...)
fld3 = fld1.regrids(fld2, 'conservative')
arr3 = fld3.array

# second iteration
fld1.set_data(...)
fld4 = fld1.regrids(fld2, 'conservative')
arr4 = fld4.array

# etc.
```

@davidhassell I was going through their documentation yesterday, and so far, the only solution I found for the caching is through a file http://earthsystemmodeling.org/esmpy_doc/release/ESMF_8_1_0/html/examples.html#read-and-write-a-weight-file where you need to specify the filename parameter in `ESMF.api.regrid.Regrid` (but I get a segfault on a laptop with macOS with esmf==8.0.1, esmpy==8.0.1 if I use this parameter). Also, I think this approach requires parallel-enabled ESMF, so this could be limiting if used in `cf`.

`ESMF.api.regrid.Regrid` also has a `get_weights_dict` method which could be useful, but I haven't been able to find a way for them to be reused later on yet (this one does not yield a segfault for me).

Thank you for considering this for your next release.
Thibault

**Comment by ThibHlln** [comment] 2021-06-02 12:28
I've done a bit of experimenting with ESMF regridding through files so I am sharing my experience here hoping it may help you.

As mentioned before, I am getting a segfault problem when using `Regrid` with a value for parameter *filename*.

I tried to bypass this problem by creating the weights file myself from the dictionary returned by `get_weights_dict` as follows:
```python
regrid_src2dst = ESMF.Regrid(
    src_field, dst_field, factors=True
    ...
)

d = regrid_src2dst.get_weights_dict()

with netCDF4.Dataset(filename, 'w') as ds:
    ds.createDimension('n_s', len(d['weights']))
    s = ds.createVariable('S', np.float64, ('n_s',))
    s[:] = d['weights']
    col = ds.createVariable('col', np.int32, ('n_s',))
    col[:] = d['col_src']
    row = ds.createVariable('row', np.int32, ('n_s',))
    row[:] = d['row_dst']

regrid_src2dst = ESMF.RegridFromFile(src_field, dst_field, filename=filename)
```
But I get the same segfault problem on the last line.

However, if I use the "RouteHandle" file instead, I don't get any problem. For example:
```python
regrid_src2dst = ESMF.Regrid(
    src_field, dst_field, rh_filename=rh_filename
    ...
)

regrid_src2dst = ESMF.RegridFromFile(src_field, dst_field, rh_filename=rh_filename)
```
I still need to understand why I am having this segmentation error, but if you have to choose between using weight files or RouteHandle files, you may want to prefer the latter. 😇

**Comment by davidhassell** [comment] 2021-06-04 09:03
Hi Thibault - thanks very much for sharing this. I shall copy this in my environment and see how I get on. You have given me some good ideas on possible ways forward within cf-python.

**Comment by davidhassell** [comment] 2021-06-04 15:41
Hi Thibault

I can do for you something like:

```python
# Calculate and save the weights once ...
regrid = fld1.regrids(fld2, method='conservative', return_regrid=True)
type(regrid)  # <class 'cf.regrid.regrid.Regrid'>, a wrapper to ESMF.Regrid

# ... use them multiple times to do the regridding
fld1.set_data(...)
fld3 = fld1.regrids(regrid)
arr3 = fld3.array

# second iteration
fld1.set_data(...)
fld4 = fld1.regrids(regrid)
arr4 = fld4.array
```
Note that if the missing data distribution in `fld1` changes then when you `set_data`, then the regrid will still work but will be slower, as the weights will have to be recalculated on-the-fly for the new mask. This is an ESMPy limitation. To be able to use "dynamic" masking (i.e. being able to impose different masks over the same set of weights) is something that we've talked about with the ESMPy developers over many years, but it hasn't yet come to pass (at least I think that's the current situation - I'll double check ...).

I'm currently putting together a PR that enables this.

**Comment by ThibHlln** [comment] 2021-06-04 16:53
Hi David,

Thank you very much for already having a solution to this! This looks like a great compromise. 🙂 

I am just wondering if this is not going to be a problem for you not to call the `destroy()` methods of all the ESMF objects just for the eventuality they may be re-used? Is Python going to garbage collect them if what is returned by `regrids`/`regridc` is not bound to a name?

For my use case, the mask is not changing overtime, so that is not a problem. It would be great if ESMpy could fix that at some stage though. But I understand in their workflow, one needs to set the mask before you call the `Regrid` instance, so this must be why.

Once you are happy with your PR, if you need someone to test this, I am of course volunteering.

**Comment by davidhassell** [comment] 2021-06-04 17:53
Hi Thibault,

> Thank you very much for already having a solution to this! This looks like a great compromise. slightly_smiling_face

You're welcome. If you have any ideas about the API, or any extra functionality that you may need, just let us know. 

> I am just wondering if this is not going to be a problem for you not to call the destroy() methods of all the ESMF objects just for the eventuality they may be re-used? Is Python going to garbage collect them if what is returned by regrids/regridc is not bound to a name?

Hmm. It may be ... The `cf.Regrid` instance will call all of the required destroys in its `__del__` method, but I'm not sure what will happen if there is no variable assignment (`fld3 = fld1.regrids(fld1.regrids(fld2, method='conservative', return_regrid=True)`), although I'm not sure that there's any benefit to doing this. What would happens if you assign to `_`? I presume that next time `_` is set the original gets garbage collected as usual? 

> Although, I thought cf-python was using ESMF Regrid instance without a mask, and then applying one as post-processing?

It's somewhat better than that - the source and (optionally) the destination masks are incorporated into the `ESMF.Grid` instances and the interplay of these masks is used during the weights calculations. This means that areas adjacent to coastlines are dealt with sensibly.

> Once you are happy with your PR, if you need someone to test this, I am of course volunteering.

You're on!

**Comment by ThibHlln** [comment] 2021-06-07 08:21
> You're welcome. If you have any ideas about the API, or any extra functionality that you may need, just let us know.

The API looks intuitive to me, and no different to what I am used to with `cf-python`. I cannot think of any additional functionality at this stage. 

> Hmm. It may be ... The cf.Regrid instance will call all of the required destroys in its __del__ method, but I'm not sure what will happen if there is no variable assignment (fld3 = fld1.regrids(fld1.regrids(fld2, method='conservative', return_regrid=True)), although I'm not sure that there's any benefit to doing this. What would happens if you assign to _? I presume that next time _ is set the original gets garbage collected as usual?

Yes, I think you are right, if all the detroys are called in `__del__` this should be just fine.

**Comment by davidhassell** [comment] 2021-06-07 16:06
Hi Thibault - I'd be great if you could test what I have done so far. 

You can get my `regrid` branch with:

```shell
$ # Check that this goes where you expect it to!
$ pip install git+https://github.com/davidhassell/cf-python@regrid --user
```

Here's how I've been testing it (which should be reproducible):

```python
In [19]: import cf

In [20]: assert cf.__version__ == '3.10.0+regrid'

In [21]: f = cf.read('regrid_file1.nc')[0]  # find the file in the `cf/test` directory

In [22]: g = cf.read('regrid_file2.nc')[0]  # find the file in the `cf/test` directory

In [23]: f, g
Out[23]: 
(<CF Field: air_temperature(time(1), latitude(64), longitude(128)) K>,
 <CF Field: air_temperature(time(1), latitude(73), longitude(96)) K>)

In [24]: h = f.regrids(g, 'conservative')

In [25]: r = f.regrids(g, 'conservative', return_operator=True)

In [26]: r
Out[26]: <cf.regrid.regridoperator.RegridOperator at 0x7f5d989d1850>

In [27]: i = f.regrids(r, 'conservative')

In [28]: i.equals(h)
Out[28]: True

In [29]: %timeit h = f.regrids(g, 'conservative')
690 ms ± 7.93 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [30]: %timeit r = f.regrids(g, 'conservative', return_operator=True)
683 ms ± 9.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [31]: %timeit i = f.regrids(r, 'conservative')
31.5 ms ± 265 µs per loop (mean ± std. dev. of 7 runs, 10 loops each) 
```

I'm still working on some comprehensive unit tests.

Thanks.

**Comment by ThibHlln** [comment] 2021-06-08 08:47
Hi David,

This works like a charm. 🐍 
I have also tried with my own (larger) fields, and it works effortlessly too.

I am just wondering if this is intentional that the *method* is not optional when using a `RegridOperator`?
```python
>>> r = f.regrids(g, 'conservative', return_operator=True)
>>> i = f.regrids(r)
ValueError: Can't regrid: Must select a regridding method
```

Also, I am sure you were planning on it, but if one uses a regridding method that is different from the one in the `RegridOperator`, the exception raised would benefit from being more informative:
 ```python
>>> r = f.regrids(g, 'conservative', return_operator=True)
>>> i = f.regrids(r, 'linear')
TypeError: exceptions must derive from BaseException
```

Thanks a lot for working on this David.

**Comment by davidhassell** [comment] 2021-06-08 18:21
Hi Thibault. Thanks. You're right about the `method` - in the next version you won't have to specify nor any of the other keyword arguments,which are just as important).

**Comment by davidhassell** [comment] 2021-06-09 14:31
Hi Thibault, could you try the latest from the "regrid" branch? You should now be able to do:

```python
op = f.regrids(g, method='linear')
g = f.regrids(op)
```

There is still scope for optionally providing additional keywords that do not contribute to regrid operator argument (such as `axis_order`). 

If you give it the thumbs-up I'll create a pull request. 

Thanks,
David

**Comment by ThibHlln** [comment] 2021-06-09 14:59
Thanks David.

I am assuming you meant to have `return_operator=True` on the first line?

It all looks good to me. 
I've tried the second line with no method, with the same method as in line 1, and with a different method from line 1, and I get what I expect each time:. regridding, regridding, and informative error message, respectively. 👍

In which cf release do you think this new functionality will be included?

**Comment by davidhassell** [comment] 2021-06-09 15:23
Hi Thibault,

Thanks - and I've edited the [previous post](https://github.com/NCAS-CMS/cf-python/issues/222#issuecomment-857746652) to include that missing keyword!

This change will be in 3.10.0. This needs to be dicussed with @sadielbartholomew, but I would have thought that this can be much sooner rather than later. We'll keep you posted.

**Comment by ThibHlln** [comment] 2021-06-23 16:43
Hi David and Sadie,

Using the regrid methods repeatedly results in a memory leak. The ESMF fields and grids created during each call to `regrids`/`regridc` do not call their `destroy()` methods, and since memory is allocated in Fortran (I think), Python garbage collection cannot do anything about it.

If I move `srcgrid.destroy()`, `srcfracfield.destroy()`, and  `srcfield.destroy()` outside of this conditional block, the memory leak disappears:
https://github.com/NCAS-CMS/cf-python/blob/d9cde28d9abd9cfeb6575c737560956f40620942/cf/field.py#L16067-L16074

Actually, I am not sure why this `destroy_old_Regrid` is required, I would probably destroy all the memory allocated by ESMF at the end of `regrids`/`regridc` (except when regridding with a `RegridOperator`). In that case, this would look like this:
```python
srcgrid.destroy()
srcfracfield.destroy()
srcfield.destroy()

if not dst_regrid:
    regridSrc2Dst.destroy()
    dstgrid.destroy()
    dstfracfield.destroy()
    dstfield.destroy()
```

If you would like me to submit a PR for this, I am more than happy to try to come up with something.

**Comment by sadielbartholomew** [comment] 2021-06-23 17:33
Very interesting discovery, thanks again @ThibHlln. Was the memory leak present before the PR that addressed your request from this Issue (i.e. #223) or is it longer-standing (i.e. is it new to v. 3.10.0)? Or are you not sure (I can investigate as it will be useful to know).

I strongly suspect @davidhassell, and I certainly, would be very happy if you were able to submit a PR with a fix! Especially since you already seem to have a good idea about the underlying problem. And I for one don't know any Fortran :grin:

**Comment by ThibHlln** [comment] 2021-06-24 07:45
> Very interesting discovery, thanks again @ThibHlln. Was the memory leak present before the PR that addressed your request from this Issue (i.e. #223) or is it longer-standing (i.e. is it new to v. 3.10.0)? Or are you not sure (I can investigate as it will be useful to know).

I think the memory leak was not present before according to the code below (from release v3.9.0), i.e. it looks like the memory release was done systematically:
https://github.com/NCAS-CMS/cf-python/blob/31b5e1c72d71fcd7efcb25c78ad17f26f47c6367/cf/field.py#L16990-L16996

> I strongly suspect @davidhassell, and I certainly, would be very happy if you were able to submit a PR with a fix! Especially since you already seem to have a good idea about the underlying problem. And I for one don't know any Fortran that would allow me to diagnose any issues relating to ESMF like you have done 😁

Ok, I will submit a PR with what I think should fix it. 🙂

**Comment by sadielbartholomew** [comment] 2021-06-24 13:13
> I think the memory leak was not present before

Ah, in which case sorry for not spotting that in review for the update for this Issue. It would be very appreciated if you put in a fix, I look forward to seeing the PR.

**Closed** 2021-07-28 12:37 UTC
Labels: enhancement, performance, question
