### ISSUE TITLE
um to netcdf - ncdimensions missing

### ISSUE THREAD

**Issue by magdalenagruziel** [NCAS-CMS/cf-python#129] opened 2020-10-05 11:14 UTC
Hello, 

I am trying to read UM file using cf-python [successfully],
and write it as netcdf file [without success]

the content of UN file is a list of fields.
I want to write them together, as they are in UM file.

In principle, cf-python starts to write the file [it exists in the path]
but the file contains only the first field. The 
cf.write(ff, 'test.nc') line [where ff is my file read with cf.read()] invokes the error:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cf/read_write/write.py", line 658, in write
    extra_write_vars=extra_write_vars)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 4291, in write
    for f in fields:
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 3205, in _write_field
    aux_coord,
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cf/read_write/netcdf/netcdfwrite.py", line 247, in _write_auxiliary_coordinate
    return super()._write_auxiliary_coordinate(f, key, coord, coordinates)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 1972, in _write_auxiliary_coordinate
    extra = self._write_bounds(f, coord, key, ncdimensions, ncvar)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 1253, in _write_bounds
    omit=omit)
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 2387, in _write_netcdf_variable
    ncdimensions_basename = [ncdim.split('/')[-1]
  File "/home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/read_write/netcdf/netcdfwrite.py", line 2387, in <listcomp>
    ncdimensions_basename = [ncdim.split('/')[-1]
AttributeError: 'NoneType' object has no attribute 'split'
`

which is weird, and not weird.

e.g. ff[0].ncdimensions, [so the nc dims of the first field in the file]
returns {}, which I understand - no nc dimensions defined for the field,
and therefore I understand the error message. Nothing to split ;)

On the other hand, all the neccessary info I can read from the field,
there are dimensions, dimension coordinates, their identities, 
so it is easy to create the neccessary ncdimensions.

Of course, I can accept, that ncdimensions is empty, and
I can create the dictionary that would contain these dimensions.

However, I have no idea how to set them. 
[how to set my dictionary as ncdimensions]

I would be very greatfull for help.

**Comment by davidhassell** [comment] 2020-10-05 13:09
Hi @magdalenagruziel, could you post the output of `cf.environment(paths=False)`, please? That should tell me all I need to know about which versions, etc. you use using.

Thanks.

**Comment by magdalenagruziel** [comment] 2020-10-05 13:54
Hi @davidhassell,
thanks for your reply, here is the output:

`Platform: Linux-4.2.0-27-generic-x86_64-with-debian-jessie-sid
HDF5 library: 1.10.5
netcdf library: 4.6.3
udunits2 library: libudunits2.so.0
python: 3.7.2 /home/magd/test-dask/venv/bin/python
netCDF4: 1.5.4 /home/magd/test-dask/venv/lib/python3.7/site-packages/netCDF4/__init__.py
cftime: 1.2.1 /home/magd/test-dask/venv/lib/python3.7/site-packages/cftime/__init__.py
numpy: 1.19.2 /home/magd/test-dask/venv/lib/python3.7/site-packages/numpy/__init__.py
psutil: 5.7.2 /home/magd/test-dask/venv/lib/python3.7/site-packages/psutil/__init__.py
scipy: 1.5.2 /home/magd/test-dask/venv/lib/python3.7/site-packages/scipy/__init__.py
matplotlib: 3.3.2 /home/magd/test-dask/venv/lib/python3.7/site-packages/matplotlib/__init__.py
ESMF: not available
cfdm: 1.8.6.0 /home/magd/test-dask/venv/lib/python3.7/site-packages/cfdm/__init__.py
cfunits: 3.2.9 /home/magd/test-dask/venv/lib/python3.7/site-packages/cfunits/__init__.py
cfplot: not available
cf: 3.6.0 /home/magd/test-dask/venv/lib/python3.7/site-packages/cf/__init__.py
`
thanks.

**Comment by sadielbartholomew** [comment] 2020-10-05 14:39
Hi @magdalenagruziel, just to jump in to provide some clarification. Based on the above I am quite confident this is a bug that we have already fixed for the upcoming version of cfdm and therefore will be fixed for the next release of cf-python. It originates from cfdm as you can see from the traceback. The fix went into cfdm as part of a large PR but the note in the Changelog was added here: https://github.com/NCAS-CMS/cfdm/commit/8d79f750cf590a3749587a16996ccfdc292d119f (though perhaps I can generalise the description of the bug slightly given your report).

You ask about a workaround you can use at the present. Of course, when the next set of versions are released they will incorporate the fix and everything will work smoothly. But as for a workaround you can use now, let me just have a think about the simplest approach. David or myself will get back to you shortly will a suggestion. Thanks.

**Comment by magdalenagruziel** [comment] 2020-10-05 14:54
Hi @sadielbartholomew, great, thanks. I would be gratefull for a workaround. Yes, I noticed that the cfdm is a source of problems. So, possibly, if you could point me to changes in the code relevant for this bug only (if this i not too many), I could simply change my local cfcm/.../netcdfwrite.py. thanks.

**Comment by sadielbartholomew** [comment] 2020-10-05 15:41
> So, possibly, if you could point me to changes in the code relevant for this bug only (if this i not too many), I could simply change my local cfcm/.../netcdfwrite.py. thanks

Sure, if you are indeed happy and prefer to use a local patch then I think all it should take to fix (I'm not certain since the fix went in as part of a larger PR so I am trying to isolate the changes which fixed it and there may need to be a few other changes too, but hopefully not) is to change `ncdim.split('/')[-1]` to `self._remove_group_structure(ncdim)`, i.e. as a `diff`:

```diff
-       ncdimensions_basename = [ncdim.split('/')[-1]
+       ncdimensions_basename = [self._remove_group_structure(ncdim)
                                 for ncdim in ncdimensions]
```

Does that do the trick?

**Comment by sadielbartholomew** [comment] 2020-10-05 15:44
(At version 1.8.6.0 of `cfdm` that should be on lines 2554-2555: https://github.com/NCAS-CMS/cfdm/blob/40e11524e02f413d726964e211410ac71b3721b9/cfdm/read_write/netcdf/netcdfwrite.py#L2386-L2387)

**Comment by magdalenagruziel** [comment] 2020-10-06 05:07
Thanks @sadielbartholomew, unfortunately it does not the trick. The probem is, that the splitting is simpy moved to the function _remove_group_structure, so it fails there. I added there condition, sth like 'if name is not None', condition works but then the writing fails futher, when joining the ncdimensions [my version lines 2411-2414].
I guess, it would be better to be able to add the ncdimensions dictionary to the fields..

**Comment by sadielbartholomew** [comment] 2020-10-06 17:14
Ah I see, sorry @magdalenagruziel  I was being naive about how easy it was to fix! This time I'll be thorough and get a development branch in the equivalent state as `cfdm` version 1.8.6.0, create a dataset where the bug appears, and tweak the codebase until I get a patch that I know for sure works. I should be able to get back to you later this (UK time) evening with that. Thanks.

**Comment by sadielbartholomew** [comment] 2020-10-06 21:43
Okay I have re-created the issue on the relevant versions with a simple script which writes out multiple fields using `cf` (not shown, it first runs `cf.environment(paths=False)` just to confirm versions):

```console
$ python failing-script.py 
Platform: Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid
HDF5 library: 1.10.5
netcdf library: 4.6.3
udunits2 library: /home/sadie/anaconda3/lib/libudunits2.so.0
python: 3.7.6
netCDF4: 1.5.4
cftime: 1.2.1
numpy: 1.19.1
psutil: 5.7.0
scipy: 1.5.0
matplotlib: 3.1.3
ESMF: 8.0.1
cfdm: 1.8.6.0
cfunits: 3.2.9
cfplot: 3.0.25
cf: 3.6.0
Traceback (most recent call last):
  File "failing-script.py", line 144, in <module>
    cf.write([Q, P], 'test_write.nc')
  File "/home/sadie/cfdm/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/home/sadie/anaconda3/lib/python3.7/site-packages/cf/read_write/write.py", line 658, in write
    extra_write_vars=extra_write_vars)
  File "/home/sadie/cfdm/cfdm/decorators.py", line 170, in verbose_override_wrapper
    return method_with_verbose_kwarg(self, *args, **kwargs)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 4291, in write
    self._write_field(f)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 3472, in _write_field
    extra=extra, data_variable=True)
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2387, in _write_netcdf_variable
    for ncdim in ncdimensions]
  File "/home/sadie/cfdm/cfdm/read_write/netcdf/netcdfwrite.py", line 2387, in <listcomp>
    for ncdim in ncdimensions]
AttributeError: 'NoneType' object has no attribute 'split'
```

and I've confirmed that the following one-line change on line 694 of your local `netcdfwrite` file, i.e. the state of it at tagged version 1.8.6.0, resolves it (it would take quite a bit of text to explain why it does the trick, so forgive me but I'll omit the explanation):

```diff
diff --git a/cfdm/read_write/netcdf/netcdfwrite.py b/cfdm/read_write/netcdf/netcdfwrite.py
index c3780f634..15e8a087a 100644
--- a/cfdm/read_write/netcdf/netcdfwrite.py
+++ b/cfdm/read_write/netcdf/netcdfwrite.py
@@ -691,7 +691,7 @@ class NetCDFWrite(IOWrite):
         g['key_to_ncvar'][key] = ncvar
         g['key_to_ncdims'][key] = ncdimensions
 
-        g['axis_to_ncdim'][axis] = ncdim
+        g['axis_to_ncdim'][axis] = seen[id(coord)]['ncdims'][0]
 
         return ncvar
```

So that should fix it for now. More importantly, we hope to release the latest versions where the bug is not present next week. So there is not long to wait until you do not need to use a patch.

I hope that sorts everything. If so, I can close this issue. Thanks.

**Comment by magdalenagruziel** [comment] 2020-10-08 07:19
Hi @sadielbartholomew, thanks, that solved the issue! please, close it.

**Closed** 2020-10-08 14:24 UTC
Labels: question
