### ISSUE TITLE
select_by_ncvar() appears to have a bug

### ISSUE THREAD

**Issue by bnlawrence** [NCAS-CMS/cf-python#79] opened 2020-05-23 06:42 UTC
In an attempt to get a specific field from [this file](https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/netcdf/IBTrACS.ALL.v04r00.nc), using the `select_by_ncvar` an error is raised:
```
 f = dataset.select_by_ncvar('sid')                                                                                                                                                        
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-16-1a2799d3f6e7> in <module>
----> 1 f = dataset.select_by_ncvar('sid')

~/anaconda3/lib/python3.7/site-packages/cf/fieldlist.py in select_by_ncvar(self, *rank)
    848 
    849         '''     
--> 850         return type(self)(f for f in self if f.match_by_ncvar(*ncvars))
    851 
    852 

~/anaconda3/lib/python3.7/site-packages/cf/fieldlist.py in __init__(self, fields)
     51                 self.append(fields)
     52             else:
---> 53                 self.extend(fields)
     54 
     55 

~/anaconda3/lib/python3.7/site-packages/cf/fieldlist.py in <genexpr>(.0)
    848 
    849         '''     
--> 850         return type(self)(f for f in self if f.match_by_ncvar(*ncvars))
    851 
    852 

NameError: name 'ncvars' is not defined
```
this is for cf.__version__ = 3.0.1

**Comment by bnlawrence** [comment] 2020-05-23 06:43
(I should say, this is after hacking the file using the hack in #78 )

**Comment by kinow** [comment] 2020-05-23 09:46
Duplicate of #76? (not released I think)

**Comment by davidhassell** [comment] 2020-05-23 19:18
Thanks, it is indeed a duplicate of #76, and will fixed in the release in a week or two.

The workaround is :
```
f = dataset.select('ncvar%sid')
```

**Closed** 2020-05-26 14:58 UTC
Labels: bug
